// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChT8R3rKzO0txW_x0gGtdGLM215k7KydI',
    appId: '1:1066545027551:web:348d64bbeffb38d62b0c6a',
    messagingSenderId: '1066545027551',
    projectId: 'bae-dating-app-53c7a',
    authDomain: 'bae-dating-app-53c7a.firebaseapp.com',
    storageBucket: 'bae-dating-app-53c7a.appspot.com',
    measurementId: 'G-BDLSW3TV0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkdH-cIFBKcZqszhm2vxzOks6i9BBrdgg',
    appId: '1:1066545027551:android:dfeee992b55769482b0c6a',
    messagingSenderId: '1066545027551',
    projectId: 'bae-dating-app-53c7a',
    storageBucket: 'bae-dating-app-53c7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJje3tQUP1gm1XgbjBNWWGqnD8_Ryqa38',
    appId: '1:1066545027551:ios:2ce044e6beaac0892b0c6a',
    messagingSenderId: '1066545027551',
    projectId: 'bae-dating-app-53c7a',
    storageBucket: 'bae-dating-app-53c7a.appspot.com',
    iosClientId: '1066545027551-60ciledbcq69565687kqbqer7p4fi3l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.beaDating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJje3tQUP1gm1XgbjBNWWGqnD8_Ryqa38',
    appId: '1:1066545027551:ios:2ce044e6beaac0892b0c6a',
    messagingSenderId: '1066545027551',
    projectId: 'bae-dating-app-53c7a',
    storageBucket: 'bae-dating-app-53c7a.appspot.com',
    iosClientId: '1066545027551-60ciledbcq69565687kqbqer7p4fi3l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.beaDating',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChT8R3rKzO0txW_x0gGtdGLM215k7KydI',
    appId: '1:1066545027551:web:b66100ab7d3974bb2b0c6a',
    messagingSenderId: '1066545027551',
    projectId: 'bae-dating-app-53c7a',
    authDomain: 'bae-dating-app-53c7a.firebaseapp.com',
    storageBucket: 'bae-dating-app-53c7a.appspot.com',
    measurementId: 'G-DEZ5FSY3C4',
  );

}