// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd5gAawOcwDWFmCNmD13ktd9HBDWNKyl8',
    appId: '1:1052128563042:web:cf1b0848578c681bdf263b',
    messagingSenderId: '1052128563042',
    projectId: 'bae-dating-cc1f5',
    authDomain: 'bae-dating-cc1f5.firebaseapp.com',
    storageBucket: 'bae-dating-cc1f5.appspot.com',
    measurementId: 'G-R8XH806XV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQHnUKkEyVx4hnrkrkniAhaOJOEtVnTk',
    appId: '1:1052128563042:android:29f1c5ad3d1393c5df263b',
    messagingSenderId: '1052128563042',
    projectId: 'bae-dating-cc1f5',
    storageBucket: 'bae-dating-cc1f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzvmAZreuEAxNTothWJmdr5-Yom-3quqM',
    appId: '1:365522137904:ios:1e2f0334023ad7e2d80ef5',
    messagingSenderId: '365522137904',
    projectId: 'bae-datingapp-b64d2',
    storageBucket: 'bae-datingapp-b64d2.appspot.com',
    iosBundleId: 'com.example.beaDating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzvmAZreuEAxNTothWJmdr5-Yom-3quqM',
    appId: '1:365522137904:ios:1e2f0334023ad7e2d80ef5',
    messagingSenderId: '365522137904',
    projectId: 'bae-datingapp-b64d2',
    storageBucket: 'bae-datingapp-b64d2.appspot.com',
    iosBundleId: 'com.example.beaDating',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP5MdCPEsNNOWxnbvRv_7x4sbDKpUcgVQ',
    appId: '1:365522137904:web:41ca1f4fbda524d0d80ef5',
    messagingSenderId: '365522137904',
    projectId: 'bae-datingapp-b64d2',
    authDomain: 'bae-datingapp-b64d2.firebaseapp.com',
    storageBucket: 'bae-datingapp-b64d2.appspot.com',
    measurementId: 'G-WDBJEXKQV3',
  );
}